name: taste
description: A simple command-line application.
version: 0.9.0
homepage: https://yadunandan.xyz

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.9.0
